<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>mouse-click.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="mouse-click.ico" />
  </ItemGroup>

</Project>